export const DO_NOT_TRANSLATE = new Set([
  'minecraft',
  'forge',
  'fabric',
  'quilt',
  'neoforge',
  'kubejs',
  'ftb',
  'hqm',
  'rf',
  'eu',
  'ae2',
  'mekanism',
  'create',
  'jei',
  'emi',
])

export const MINECRAFT_TRANSLATIONS: Record<string, string> = {
  'Diamond Sword': 'Épée en diamant',
  'Iron Ingot': 'Lingot de fer',
  'Crafting Table': 'Établi',
  Inventory: 'Inventaire',
  Furnace: 'Fourneau',
  Chest: 'Coffre',
  Hopper: 'Entonnoir',
  Anvil: 'Enclume',
  Enchantment: 'Enchantement',
  'Enchanting Table': 'Table d enchantement',
  'Nether Portal': 'Portail du Nether',
  'End Portal': 'Portail de l End',
  'Redstone Dust': 'Poudre de redstone',
  'Golden Apple': 'Pomme doree',
  Bread: 'Pain',
  Arrow: 'Fleche',
  Bow: 'Arc',
  Pickaxe: 'Pioche',
  Axe: 'Hache',
  Shovel: 'Pelle',
  Hoe: 'Houe',
  Helmet: 'Casque',
  Chestplate: 'Plastron',
  Leggings: 'Jambieres',
  Boots: 'Bottes',
  Villager: 'Villageois',
  Zombie: 'Zombie',
  Skeleton: 'Squelette',
  Creeper: 'Creeper',
  Spider: 'Araignee',
  Blaze: 'Blaze',
  Ghast: 'Ghast',
  Enderman: 'Enderman',
  Wither: 'Wither',
  Dragon: 'Dragon',
  'Oak Planks': 'Planches de chene',
  'Spruce Planks': 'Planches de sapin',
  'Birch Planks': 'Planches de bouleau',
  'Jungle Planks': 'Planches d acajou',
  'Acacia Planks': 'Planches d acacia',
  'Dark Oak Planks': 'Planches de chene noir',
  Stone: 'Pierre',
  Cobblestone: 'Pierre taillee',
  Sand: 'Sable',
  Gravel: 'Gravier',
  Dirt: 'Terre',
  Grass: 'Herbe',
  Water: 'Eau',
  Lava: 'Lave',
  Coal: 'Charbon',
  Iron: 'Fer',
  Gold: 'Or',
  Diamond: 'Diamant',
  Emerald: 'Émeraude',
  Quartz: 'Quartz',
  Obsidian: 'Obsidienne',
  Bedrock: 'Roche mere',
  Biome: 'Biome',
  Plains: 'Plaines',
  Desert: 'Desert',
  Forest: 'Foret',
  Taiga: 'Taiga',
  Swamp: 'Marais',
  Jungle: 'Jungle',
  Savanna: 'Savane',
  Mountains: 'Montagnes',
  Ocean: 'Ocean',
  River: 'Riviere',
  Dungeon: 'Donjon',
  Temple: 'Temple',
  Fortress: 'Forteresse',
  Bastion: 'Bastion',
  'Stronghold': 'Forteresse souterraine',
  advancement: 'avancement',
  quest: 'quete',
  reward: 'recompense',
  chapter: 'chapitre',
  machine: 'machine',
  automation: 'automatisation',
  energy: 'energie',
  generator: 'generateur',
  battery: 'batterie',
  cable: 'cable',
  pipe: 'tuyau',
  tank: 'reservoir',
  fluid: 'fluide',
  gear: 'engrenage',
  plate: 'plaque',
  ingot: 'lingot',
  dust: 'poudre',
  nugget: 'pepites',
  casing: 'boitier',
  alloy: 'alliage',
}

export function getGlossaryTranslation(text: string): string | null {
  const normalized = text.trim().toLowerCase()
  const direct = Object.entries(MINECRAFT_TRANSLATIONS).find(([k]) => k.trim().toLowerCase() === normalized)
  if (direct) return direct[1]
  return null
}

export const applyGlossary = getGlossaryTranslation
